######################################################################
# Automatically generated by qmake (3.0) ?? 2? 3 15:48:09 2018
######################################################################
QT+=widgets

TEMPLATE = app
TARGET = MyNode
INCLUDEPATH += .

# Input
HEADERS += finddialog.h mynote.h
FORMS += mynote.ui
SOURCES += finddialog.cpp main.cpp mynote.cpp
RESOURCES += images.qrc


RC_ICONS = log.ico
